export const SESSION_LIST_ROW_HEIGHT_DEFAULT = 84;
export const SESSION_LIST_ROW_HEIGHT_COMPACT = 58;
export const SESSION_LIST_ROW_HEIGHT_MINIMAL = 34;
export const SESSION_LIST_ROW_HEIGHT_MINIMAL_PHONE = 48;

export const SESSION_LIST_DIRECTORY_ROW_HEIGHT = 44;
